/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGra;

import Contro.Controladora;
import Contro.Items;
import Contro.Personas;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class PrestamoEliminar extends javax.swing.JFrame {

    private Controladora con;
    private ArrayList<Personas> personas = new ArrayList();
        
    private DefaultTableModel modeloPersonas;
    private DefaultTableModel modeloPrestamos;
    private int numPrestamo;
    private ArrayList<Items> itemsArray;
    
    
    public PrestamoEliminar() {
        initComponents();
        modeloPersonas = (DefaultTableModel)tblPersonas.getModel();
        modeloPrestamos = (DefaultTableModel)tblPrestamos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnEliminarPrestamo = new javax.swing.JButton();
        cbItems = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnEliminarItems = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prestamo", "Alarma", "Items"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPrestamosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPrestamos);

        tblPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPersonas);

        jButton1.setText("Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEliminarPrestamo.setText("Eliminar Prestamo");
        btnEliminarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPrestamoActionPerformed(evt);
            }
        });

        cbItems.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--------------" }));

        jLabel1.setText("Items:");

        btnEliminarItems.setText("Eliminar Items");
        btnEliminarItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarItemsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jLabel2.setText("Eliminar Prestamo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarPrestamo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEliminarItems)
                                    .addComponent(jLabel1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel2)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarItems)
                        .addGap(50, 50, 50)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonasMouseClicked
        // TODO add your handling code here:
        cbItems.removeAllItems();
        cbItems.addItem("--------------");
        int totalFilas = modeloPrestamos.getRowCount();
        for (int i =totalFilas; i>0; i--){
            modeloPrestamos.removeRow(i-1);
        }
        numPrestamo = -1;
        btnEliminarItems.setEnabled(false);

        String nombre = String.valueOf(modeloPersonas.getValueAt(tblPersonas.getSelectedRow(), 0));
        for (Personas persona: personas){
            if (persona.getNombre().equals(nombre)){
                for (int i=0; i<persona.getNumPrestamos(); i++){
                    modeloPrestamos.insertRow(modeloPrestamos.getRowCount(), new Object[]{i+1,persona.getPrestamos().get(i).toStringAlarma() ,persona.getPrestamos().get(i).toStringItems() });
                    
                }
            }
        }
    }//GEN-LAST:event_tblPersonasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        VentanaPrin abrir = new VentanaPrin ();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btnEliminarPrestamo.setEnabled(false);
        btnEliminarItems.setEnabled(false);
        con = VentanaPrin.getCon();
        personas = con.getPersonas();
        for (int i = 0; i < personas.size(); i++){
        modeloPersonas.insertRow(modeloPersonas.getRowCount(), new Object[]{personas.get(i).getNombre()});
        numPrestamo = -1;
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    private void tblPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrestamosMouseClicked
        // TODO add your handling code here:
        cbItems.removeAllItems();
        cbItems.addItem("--------------");
        numPrestamo = tblPrestamos.getSelectedRow();
        btnEliminarPrestamo.setEnabled(true);
        btnEliminarItems.setEnabled(true);
        itemsArray = con.getPrestamos(tblPersonas.getSelectedRow(), numPrestamo).getItems();
        for (Items item: itemsArray){
            cbItems.addItem(item.getNombre());
        }
        
    }//GEN-LAST:event_tblPrestamosMouseClicked

    private void btnEliminarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPrestamoActionPerformed
        // TODO add your handling code here:
        cbItems.removeAllItems();
        cbItems.addItem("--------------");
        if (numPrestamo != -1){
            con.eliminarPrestamo(tblPersonas.getSelectedRow(), numPrestamo);
            JOptionPane.showMessageDialog(this, "El Prestamo se ha eliminado correctamente", "Información", 1);
            int totalFilas = modeloPrestamos.getRowCount();
            for (int i =totalFilas; i>0; i--){
                modeloPrestamos.removeRow(i-1);
            }
            numPrestamo = -1;
            btnEliminarPrestamo.setEnabled(false);
            btnEliminarItems.setEnabled(false);

            String nombre = String.valueOf(modeloPersonas.getValueAt(tblPersonas.getSelectedRow(), 0));
            for (Personas persona: personas){
                if (persona.getNombre().equals(nombre)){
                    for (int i=0; i<persona.getNumPrestamos(); i++){
                        modeloPrestamos.insertRow(modeloPrestamos.getRowCount(), new Object[]{i+1,persona.getPrestamos().get(i).toStringAlarma() ,persona.getPrestamos().get(i).toStringItems() });
                    }

                }
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un prestamo", "Error", 0);
        }
    }//GEN-LAST:event_btnEliminarPrestamoActionPerformed

    private void btnEliminarItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarItemsActionPerformed
        // TODO add your handling code here:
        if(cbItems.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(this, "No ha seleccionado un ítem", "Error", 0);
        }
        else if (cbItems.getItemCount()==2){
            con.eliminarPrestamo(tblPersonas.getSelectedRow(), numPrestamo);
            JOptionPane.showMessageDialog(this, "El Item se ha eliminado correctamente", "Información", 1);
            int totalFilas = modeloPrestamos.getRowCount();
            for (int i =totalFilas; i>0; i--){
                modeloPrestamos.removeRow(i-1);
            }

            String nombre = String.valueOf(modeloPersonas.getValueAt(tblPersonas.getSelectedRow(), 0));
            for (Personas persona: personas){
                if (persona.getNombre().equals(nombre)){
                    for (int i=0; i<persona.getNumPrestamos(); i++){
                        modeloPrestamos.insertRow(modeloPrestamos.getRowCount(), new Object[]{i+1,persona.getPrestamos().get(i).toStringAlarma() ,persona.getPrestamos().get(i).toStringItems() });
                    }

                }
            }
            //itemsArray = con.getPrestamos(tblPersonas.getSelectedRow(), numPrestamo).getItems();
            //for (Items item: itemsArray){
            //    cbItems.addItem(item.getNombre());
            //}
        }
        else
        {
            con.eliminarItemPrestamo(tblPersonas.getSelectedRow(), numPrestamo, cbItems.getSelectedIndex()-1);
            JOptionPane.showMessageDialog(this, "El Item se ha eliminado correctamente", "Información", 1);
            int totalFilas = modeloPrestamos.getRowCount();
            for (int i =totalFilas; i>0; i--){
                modeloPrestamos.removeRow(i-1);
            }

            String nombre = String.valueOf(modeloPersonas.getValueAt(tblPersonas.getSelectedRow(), 0));
            for (Personas persona: personas){
                if (persona.getNombre().equals(nombre)){
                    for (int i=0; i<persona.getNumPrestamos(); i++){
                        modeloPrestamos.insertRow(modeloPrestamos.getRowCount(), new Object[]{i+1,persona.getPrestamos().get(i).toStringAlarma() ,persona.getPrestamos().get(i).toStringItems() });
                    }

                }
            }
            itemsArray = con.getPrestamos(tblPersonas.getSelectedRow(), numPrestamo).getItems();
            for (Items item: itemsArray){
                cbItems.addItem(item.getNombre());
            }
        }
        
    }//GEN-LAST:event_btnEliminarItemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrestamoEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrestamoEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrestamoEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrestamoEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrestamoEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarItems;
    private javax.swing.JButton btnEliminarPrestamo;
    private javax.swing.JComboBox cbItems;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPersonas;
    private javax.swing.JTable tblPrestamos;
    // End of variables declaration//GEN-END:variables
}
